/** Auto-synced from migration/src/data/pageMeta.ts — editable via admin Website Content. */
module.exports = {
  "home": {
    title: "Nanak Migration Group | Australian Migration Experts",
    metaDescription: "Nanak Migration Group — MARA-registered agents helping skilled workers, students and families navigate Australia",
    primaryKeyword: "Australian migration agents",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "about": {
    title: "About Nanak Migration Group | Registered Migration Agents",
    metaDescription: "Meet Navpreet Aulakh (MARN 2619467) and the Nanak Migration Group team — regulated migration advice in English, Hindi and Punjabi across Australia.",
    primaryKeyword: "Nanak Migration Group about",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "book": {
    title: "Book a Consultation | Nanak Migration Group",
    metaDescription: "Book a consultation with a MARA-registered migration agent (MARN 2619467). Choose a time online — confirmation by email. No login required.",
    primaryKeyword: "book migration consultation Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "book-consultation": {
    title: "Book a Consultation | Nanak Migration Group",
    metaDescription: "Book a consultation with a MARA-registered migration agent (MARN 2619467) about your Australian visa pathway. Skilled, employer, student and family visas.",
    primaryKeyword: "book migration consultation Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "pre-assessment": {
    title: "Pre-consult Assessment | Nanak Migration Group",
    metaDescription: "Complete your pre-consultation assessment before your appointment with Nanak Migration Group (MARN 2619467). Takes about 2 minutes.",
    primaryKeyword: "migration pre assessment form",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "contact": {
    title: "Contact Nanak Migration Group | Truganina, Geelong, Cranbourne, Canning Vale, Craigieburn",
    metaDescription: "Contact Nanak Migration Group — phone 1300 644 728 or email visa@nanakmigration.com.au. Offices in Truganina, Geelong, Cranbourne, Canning Vale and Craigieburn. MARN 2619467.",
    primaryKeyword: "contact migration agent Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "privacy": {
    title: "Privacy Policy | Nanak Migration Group",
    metaDescription: "How Nanak Migration Group Pty Ltd collects, uses and protects personal information.",
    primaryKeyword: "privacy policy",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "terms": {
    title: "Terms of Use | Nanak Migration Group",
    metaDescription: "Terms governing use of the Nanak Migration Group website.",
    primaryKeyword: "terms of use",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "accessibility": {
    title: "Accessibility | Nanak Migration Group",
    metaDescription: "Accessibility information for the Nanak Migration Group website.",
    primaryKeyword: "accessibility",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "employer-sponsored-visas": {
    title: "Employer Sponsored Visas | Nanak Migration Group",
    metaDescription: "Australian employer-sponsored visas — subclass 482 Skills in Demand, subclass 186 permanent residence, subclass 494 regional. Agent MARN 2619467.",
    primaryKeyword: "employer sponsored visas Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "employer-nomination-scheme": {
    title: "Employer Nomination Scheme (186) | Nanak Migration Group",
    metaDescription: "The subclass 186 visa grants permanent residence via employer nomination. Registered agent MARN 2619467 explains eligibility, streams and requirements.",
    primaryKeyword: "employer nomination scheme 186 visa",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "186-skill-requirements": {
    title: "186 Visa Skill Requirements | Nanak Migration Group",
    metaDescription: "Skills assessment, work experience and English requirements for the subclass 186 Employer Nomination Scheme visa in Australia. MARN 2619467.",
    primaryKeyword: "186 visa skill requirements",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "186-occupations-list": {
    title: "186 Visa Occupations List | Nanak Migration Group",
    metaDescription: "Occupations eligible for the subclass 186 Employer Nomination Scheme via the CSOL and MLTSSL. Search by ANZSCO code. Registered agent MARN 2619467.",
    primaryKeyword: "186 visa occupations list",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "skills-in-demand-visa": {
    title: "Skills in Demand Visa (482) | Nanak Migration Group",
    metaDescription: "The subclass 482 Skills in Demand visa lets employers sponsor skilled workers for up to 4 years. Streams: Core Skills, Specialist, Essential. MARN 2619467.",
    primaryKeyword: "skills in demand visa 482",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "482-core-skills-stream": {
    title: "482 Core Skills Stream — Skills in Demand Visa | Nanak Migration Group",
    metaDescription: "The Core Skills stream of the subclass 482 Skills in Demand visa requires a CSOL occupation and CSIT salary of $79,499 p.a. from 1 July 2026. Agent MARN 2619467.",
    primaryKeyword: "482 core skills stream CSOL CSIT",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "482-specialist-skills-stream": {
    title: "482 Specialist Skills Stream — Skills in Demand Visa | Nanak Migration Group",
    metaDescription: "The Specialist Skills stream of the subclass 482 visa requires earnings of $146,717 p.a. (SSIT from 1 July 2026) and is exempt from Labour Market Testing. MARN 2619467.",
    primaryKeyword: "482 specialist skills stream SSIT no LMT",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "482-to-pr-pathway": {
    title: "482 to PR Pathway — 186 TRT Stream | Nanak Migration Group",
    metaDescription: "Transition from the subclass 482 to permanent residence via the subclass 186 TRT stream. Generally requires 2 years with the same employer. MARN 2619467.",
    primaryKeyword: "482 visa to permanent residence pathway",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "standard-business-sponsorship": {
    title: "Standard Business Sponsorship (SBS) | Nanak Migration Group",
    metaDescription: "Australian businesses must hold Standard Business Sponsorship before nominating workers on a subclass 482 visa. Approval takes 4–8 weeks. MARN 2619467.",
    primaryKeyword: "standard business sponsorship Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "core-skills-occupation-list": {
    title: "Core Skills Occupation List (CSOL) | Nanak Migration Group",
    metaDescription: "The Core Skills Occupation List (CSOL) determines occupations eligible for the subclass 482 Core Skills stream. Search by ANZSCO code. MARN 2619467.",
    primaryKeyword: "core skills occupation list CSOL 482",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "labour-market-testing": {
    title: "Labour Market Testing (LMT) Requirements | Nanak Migration Group",
    metaDescription: "Labour Market Testing for subclass 482 Core Skills nominations — 28-day advertising, required platforms, exemptions and record-keeping. Agent MARN 2619467.",
    primaryKeyword: "labour market testing 482 visa requirements",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "saf-levy": {
    title: "Skilling Australians Fund (SAF) Levy | Nanak Migration Group",
    metaDescription: "SAF Levy rates for 482 and 186/494 nominations — $1,200 or $1,800 per year for 482; $3,000 or $5,000 for 186/494. Refund rules, employer obligations. MARN 2619467.",
    primaryKeyword: "SAF levy skilling australians fund 482 186",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "sponsorship-obligations": {
    title: "Sponsorship Obligations for Approved Sponsors | Nanak Migration Group",
    metaDescription: "Ongoing obligations for Standard Business Sponsors — equivalent terms, no cost recovery, record-keeping, notifiable events, sanctions. MARN 2619467.",
    primaryKeyword: "employer sponsor obligations Australia 482",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "494-visa": {
    title: "Regional Employer Sponsored Visa (Subclass 494) | Nanak Migration Group",
    metaDescription: "The subclass 494 Employer Sponsored Regional visa is a 5-year provisional visa for workers in designated regional areas. Pathway to 191 permanent residence. MARN 2619467.",
    primaryKeyword: "subclass 494 regional employer sponsored visa",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "skilling-australians-fund": {
    title: "Skilling Australians Fund (SAF) Levy Guide | Nanak Migration Group",
    metaDescription: "SAF Levy rates, payment process, exemptions and refund rules for subclass 482 and 186 employer nominations in Australia. Agent MARN 2619467.",
    primaryKeyword: "skilling australians fund levy 482 186",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "employer-obligations": {
    title: "Employer Obligations for Approved Sponsors | Nanak Migration Group",
    metaDescription: "Ongoing sponsor obligations for Standard Business Sponsors — equivalent terms, record-keeping, notification requirements and breach sanctions. MARN 2619467.",
    primaryKeyword: "employer sponsor obligations Australia 482",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "visa-conditions-482": {
    title: "482 Visa Conditions — Condition 8107 Explained | Nanak Migration Group",
    metaDescription: "Subclass 482 visa conditions — what condition 8107 means, work rights, travel entitlements, and family member rights. Registered agent MARN 2619467.",
    primaryKeyword: "482 visa conditions condition 8107",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "change-of-employer": {
    title: "Change of Employer on a Subclass 482 Visa | Nanak Migration Group",
    metaDescription: "How to transfer your subclass 482 sponsorship to a new employer — the 60-day rule, new nomination requirements, and risks to avoid. MARN 2619467.",
    primaryKeyword: "change employer 482 visa sponsor transfer",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "genuine-position-test": {
    title: "Genuine Position Test for 482 Nominations | Nanak Migration Group",
    metaDescription: "How the Department of Home Affairs assesses whether a nominated position is genuine for a subclass 482 visa. Evidence guide. Agent MARN 2619467.",
    primaryKeyword: "genuine position test 482 nomination",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "labour-agreement": {
    title: "Labour Agreements — Employer Sponsorship | Nanak Migration Group",
    metaDescription: "Labour Agreements allow employers to sponsor overseas workers in occupations not available under standard 482 or 186 pathways. Types, eligibility, process. MARN 2619467.",
    primaryKeyword: "labour agreement employer sponsorship Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "labour-agreements": {
    title: "Labour Agreements — Employer Sponsorship | Nanak Migration Group",
    metaDescription: "Labour Agreements allow employers to sponsor overseas workers in occupations not available under standard 482 or 186 pathways. Types, eligibility, process. MARN 2619467.",
    primaryKeyword: "labour agreement employer sponsorship Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "skilled-migration": {
    title: "Skilled Migration to Australia | Nanak Migration Group",
    metaDescription: "Skilled migration to Australia via SkillSelect — subclass 189, 190 and 491 points-tested visas explained. Registered migration agent MARN 2619467.",
    primaryKeyword: "skilled migration Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "skilled-independent-189": {
    title: "Skilled Independent Visa (189) | Nanak Migration Group",
    metaDescription: "The subclass 189 Skilled Independent visa grants permanent Australian residence without a sponsor. Points-tested via SkillSelect. Agent MARN 2619467.",
    primaryKeyword: "skilled independent visa 189",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "skilled-nominated-190": {
    title: "Skilled Nominated Visa (190) | Nanak Migration Group",
    metaDescription: "The subclass 190 Skilled Nominated visa grants permanent residence via state or territory nomination. Adds 5 points to your EOI score. MARN 2619467.",
    primaryKeyword: "skilled nominated visa 190",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "skilled-work-regional-491": {
    title: "Skilled Work Regional Visa (491) | Nanak Migration Group",
    metaDescription: "The subclass 491 Skilled Work Regional visa requires regional living and adds 15 points. Pathway to permanent residence via subclass 191. MARN 2619467.",
    primaryKeyword: "skilled work regional visa 491",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "temporary-graduate-485": {
    title: "Temporary Graduate Visa (485) | Nanak Migration Group",
    metaDescription: "The subclass 485 Temporary Graduate visa lets graduates work in Australia after study. Streams: Post-Higher Education Work and Graduate Work. MARN 2619467.",
    primaryKeyword: "temporary graduate visa 485",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "points-test": {
    title: "Australian Points Test Explained | Nanak Migration Group",
    metaDescription: "How the Australian points test works for subclass 189, 190 and 491 visas. Minimum 65 points required for EOI. Calculator included. MARN 2619467.",
    primaryKeyword: "Australian skilled migration points test",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "skills-assessment": {
    title: "Skills Assessment for Australian Visas | Nanak Migration",
    metaDescription: "Skills assessment is required for Australian skilled and employer-sponsored visas. Guide to assessing authorities, evidence and timelines. MARN 2619467.",
    primaryKeyword: "skills assessment Australia visa",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "state-nomination": {
    title: "State Nomination Requirements | Nanak Migration Group",
    metaDescription: "State and territory nomination for the subclass 190 and 491 visas — each state sets its own occupation lists and criteria. Registered agent MARN 2619467.",
    primaryKeyword: "state nomination 190 491 visa requirements",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "english-requirements": {
    title: "English Requirements for Australian Visas | Nanak Migration",
    metaDescription: "English proficiency levels and approved test scores for Australian skilled and employer-sponsored visas, including subclass 482 and 186. MARN 2619467.",
    primaryKeyword: "English requirements Australian visa IELTS PTE",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "student-visas": {
    title: "Australian Student Visas | Nanak Migration Group",
    metaDescription: "The subclass 500 Student visa and pathways to Australian permanent residence for international students. Registered migration agent MARN 2619467.",
    primaryKeyword: "Australian student visa",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "student-visa-500": {
    title: "Student Visa (Subclass 500) | Nanak Migration Group",
    metaDescription: "The subclass 500 Student visa allows full-time study at a CRICOS-registered Australian institution with 48 hours per fortnight work rights. MARN 2619467.",
    primaryKeyword: "student visa subclass 500 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "genuine-student-requirement": {
    title: "Genuine Student Requirement (GSR) | Nanak Migration Group",
    metaDescription: "The Genuine Student requirement replaced the GTE for the subclass 500 student visa in March 2024. How to demonstrate genuine study intent. MARN 2619467.",
    primaryKeyword: "genuine student requirement subclass 500",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "student-to-pr-pathway": {
    title: "Student to PR Pathway in Australia | Nanak Migration Group",
    metaDescription: "How international students can transition to permanent residence via subclass 485, 189, 190 or employer-sponsored pathways. Registered agent MARN 2619467.",
    primaryKeyword: "student visa to permanent residence Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "courses-pr-prospects": {
    title: "Courses with PR Prospects | Nanak Migration Group",
    metaDescription: "How course choice affects your pathway to Australian permanent residence. Occupation lists, skills assessments, and the Australian Study Requirement explained. MARN 2619467.",
    primaryKeyword: "courses with PR prospects Australia international student",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "student-financial-capacity": {
    title: "Financial Capacity for Student Visas | Nanak Migration Group",
    metaDescription: "Funds evidence required for the subclass 500 student visa — living costs, course fees, travel, and acceptable evidence types. Registered agent MARN 2619467.",
    primaryKeyword: "student visa financial capacity evidence Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "student-guardian-590": {
    title: "Student Guardian Visa (Subclass 590) | Nanak Migration Group",
    metaDescription: "The subclass 590 Student Guardian visa allows a parent or relative to live in Australia to care for an international student under 18. No work rights. Requirements and process explained. MARN 2619467.",
    primaryKeyword: "student guardian visa subclass 590 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "partner-family-visas": {
    title: "Partner & Family Visas Australia | Nanak Migration Group",
    metaDescription: "Australian partner and family visas — onshore subclass 820/801, offshore 309/100, and prospective marriage subclass 300. Registered agent MARN 2619467.",
    primaryKeyword: "partner visa Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "parent-visas": {
    title: "Parent Visas Australia — All Pathways | Nanak Migration Group",
    metaDescription: "Parent visa pathways to Australia — subclass 143, 173, 103, 804, 864 and 870 explained. Costs, queues and Balance of Family test. Registered agent MARN 2619467.",
    primaryKeyword: "parent visa Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "contributory-parent-143": {
    title: "Contributory Parent Visa (Subclass 143) | Nanak Migration Group",
    metaDescription: "The subclass 143 Contributory Parent visa grants permanent residence to parents of settled Australians. Charges ~AUD 95,000 for a couple. Registered agent MARN 2619467.",
    primaryKeyword: "contributory parent visa subclass 143",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "contributory-parent-173": {
    title: "Contributory Parent (Temporary) Visa Subclass 173 | Nanak Migration Group",
    metaDescription: "The subclass 173 Contributory Parent visa is a 2-year temporary visa — the first stage of the two-step path to the permanent subclass 143. Split the large contributory charges over two applications. MARN 2619467.",
    primaryKeyword: "contributory parent visa 173 temporary Australia two stage",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "aged-parent-804": {
    title: "Aged Parent Visa (Subclass 804) | Nanak Migration Group",
    metaDescription: "The subclass 804 Aged Parent visa is an onshore, non-contributory permanent parent visa for pension-age parents. Very long queue (decades). Low charge. Honest guide. MARN 2619467.",
    primaryKeyword: "aged parent visa 804 onshore Australia permanent non-contributory",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "contributory-aged-parent-864": {
    title: "Contributory Aged Parent Visa (Subclass 864) | Nanak Migration Group",
    metaDescription: "The subclass 864 Contributory Aged Parent visa is for pension-age parents already in Australia — permanent residence with a large contributory charge and a 12-15 year wait for new applications. MARN 2619467.",
    primaryKeyword: "contributory aged parent visa 864 Australia onshore permanent",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "partner-visa-820-801": {
    title: "Partner Visa Onshore (820/801) | Nanak Migration Group",
    metaDescription: "The subclass 820/801 onshore partner visa is a two-stage visa for applicants in Australia in a genuine de facto or married relationship. MARN 2619467.",
    primaryKeyword: "partner visa onshore 820 801 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "partner-visa-309-100": {
    title: "Partner Visa Offshore (309/100) | Nanak Migration Group",
    metaDescription: "The subclass 309/100 offshore partner visa is for applicants outside Australia in a genuine relationship with an Australian citizen or PR. MARN 2619467.",
    primaryKeyword: "partner visa offshore 309 100 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "prospective-marriage-300": {
    title: "Prospective Marriage Visa (300) | Nanak Migration Group",
    metaDescription: "The subclass 300 Prospective Marriage visa allows entry to Australia to marry your partner within 9 months, then apply for a partner visa. MARN 2619467.",
    primaryKeyword: "prospective marriage visa subclass 300",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "partner-visa-evidence": {
    title: "Partner Visa Evidence Guide | Nanak Migration Group",
    metaDescription: "Evidence required for an Australian partner visa (subclass 820/801 or 309/100) across financial, household, social and commitment categories. MARN 2619467.",
    primaryKeyword: "partner visa evidence requirements Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "bridging-visas": {
    title: "Bridging Visas Explained | Nanak Migration Group",
    metaDescription: "Bridging Visa A (BVA), B (BVB) and E (BVE) allow lawful stay in Australia while a substantive visa is processed. Nanak Migration Group MARN 2619467.",
    primaryKeyword: "bridging visa Australia BVA BVB BVE",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "australian-citizenship": {
    title: "Australian Citizenship by Conferral | Nanak Migration Group",
    metaDescription: "Australian citizenship by conferral requires 4 years of lawful residence including 12 months as a permanent resident. Registered agent MARN 2619467.",
    primaryKeyword: "Australian citizenship by conferral requirements",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "visa-refusal-review": {
    title: "Visa Refusal & Review Options | Nanak Migration Group",
    metaDescription: "Australian visa refusal and cancellation — review rights, ART deadlines and merits review options. Nanak Migration Group, registered agent MARN 2619467.",
    primaryKeyword: "Australian visa refusal review appeal",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "art-review": {
    title: "ART Review — Administrative Review Tribunal | Nanak",
    metaDescription: "The Administrative Review Tribunal (ART) reviews visa refusal and cancellation decisions. A 21-day lodgement deadline generally applies. MARN 2619467.",
    primaryKeyword: "Administrative Review Tribunal ART visa review Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "191-visa": {
    title: "Permanent Residence (Skilled Regional) Subclass 191 | Nanak Migration Group",
    metaDescription: "The subclass 191 Permanent Residence (Skilled Regional) visa is for holders of a 491 or 494 visa who have lived, worked and met income requirements in a regional area for 3 years. MARN 2619467.",
    primaryKeyword: "subclass 191 permanent residence skilled regional",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "occupation-caveats": {
    title: "CSOL Occupation Caveats — 482 Nomination | Nanak Migration Group",
    metaDescription: "Occupation caveats in the Core Skills Occupation List (CSOL) restrict which employers and positions can use a listed ANZSCO code for a subclass 482 nomination. Agent MARN 2619467.",
    primaryKeyword: "CSOL occupation caveats 482 nomination",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "resources": {
    title: "Visa Guides, Blogs & Checklists | Nanak Migration Group",
    metaDescription: "Free Australian visa guides, articles and checklists written by MARA-registered agents. Browse all 30 visa guides, blog updates and evidence checklists.",
    primaryKeyword: "australian visa guides checklists",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "guides": {
    title: "Visa Guides — 30 Australian Visa Topics | Nanak Migration",
    metaDescription: "Browse all 30 Australian visa guides written by MARA-registered agents. Filterable by category — employer, skilled, student, partner, visitor and reviews.",
    primaryKeyword: "australian visa guides",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "blog": {
    title: "Migration Blog — Policy & Visa News | Nanak Migration Group",
    metaDescription: "Australian immigration news, policy updates and visa guidance from MARA-registered migration agents at Nanak Migration Group.",
    primaryKeyword: "australian immigration news",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "checklists": {
    title: "Visa Document Checklists | Nanak Migration Group",
    metaDescription: "Free Australian visa document checklists for partner, 186, student, points test, citizenship and 482-to-PR applications. General guidance only.",
    primaryKeyword: "australian visa checklist",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "tools": {
    title: "Migration Tools — Free Visa Calculators | Nanak Migration",
    metaDescription: "Free migration tools: points calculator, occupation search, residence calculator, English score converter and visa pathway comparison. Indicative only.",
    primaryKeyword: "australian visa calculator",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "national-innovation-visa": {
    title: "National Innovation Visa (Subclass 858) | Nanak Migration Group",
    metaDescription: "The National Innovation Visa (subclass 858) is a permanent residence visa for individuals with an internationally recognised record of exceptional and outstanding achievement in academia, research, sport, the arts, or innovative technology. MARN 2619467.",
    primaryKeyword: "national innovation visa subclass 858",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "skillselect-eoi": {
    title: "SkillSelect and Expressions of Interest (EOI) | Nanak Migration Group",
    metaDescription: "SkillSelect EOI explained — how expressions of interest work for subclass 189, 190 and 491 visas, invitation rounds, points ranking, and PIC 4020 risks. Registered migration agent MARN 2619467.",
    primaryKeyword: "SkillSelect expression of interest EOI Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "regional-areas": {
    title: "Designated Regional Areas for Australian Visas | Nanak Migration Group",
    metaDescription: "Which Australian postcodes qualify as designated regional areas for 491, 494 and 191 visas — definitions, exclusions, living requirements, and DAMA access. Registered migration agent MARN 2619467.",
    primaryKeyword: "designated regional area Australian immigration visa",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "sponsored-parent-870": {
    title: "Sponsored Parent (Temporary) Visa — Subclass 870 | Nanak Migration Group",
    metaDescription: "The subclass 870 Sponsored Parent (Temporary) visa allows a parent to live in Australia for up to 10 years — no Balance of Family test required. Registered agent MARN 2619467.",
    primaryKeyword: "sponsored parent visa subclass 870 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "balance-of-family-test": {
    title: "Balance of Family Test Explained | Nanak Migration Group",
    metaDescription: "How the Balance of Family test works for Australian parent visas — who counts, two ways to pass, which visa subclasses require it, and what to do if you fail. Registered agent MARN 2619467.",
    primaryKeyword: "balance of family test parent visa Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "visitor-visas": {
    title: "Visitor Visas Hub — eVisitor, ETA & Subclass 600 | Nanak Migration Group",
    metaDescription: "Australian visitor visas compared — eVisitor (651), ETA (601) and Visitor visa (subclass 600). Choose the right option for your passport and stay. Registered migration agent MARN 2619467.",
    primaryKeyword: "visitor visa Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "visitor-visa-600": {
    title: "Visitor Visa (Subclass 600) | Nanak Migration Group",
    metaDescription: "The subclass 600 Visitor visa is available to all nationalities — tourist, sponsored family, business visitor and frequent traveller streams. Stays of 3, 6 or 12 months. Registered agent MARN 2619467.",
    primaryKeyword: "visitor visa subclass 600 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "resident-return-visa": {
    title: "Resident Return Visa (Subclass 155 & 157) | Nanak Migration Group",
    metaDescription: "The Resident Return Visa (subclass 155 or 157) lets Australian permanent residents re-enter Australia after their 5-year travel facility expires. Registered agent MARN 2619467.",
    primaryKeyword: "resident return visa Australia subclass 155 157",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "visa-cancellation": {
    title: "Visa Cancellation Australia — NOICC Response | Nanak Migration Group",
    metaDescription: "Australian visa cancellation under s116, s109 and s501 — NOICC response guide, ART review rights and consequences including the section 48 bar. Registered agent MARN 2619467.",
    primaryKeyword: "visa cancellation Australia NOICC response",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "section-48-bar": {
    title: "Section 48 Bar — Exempt Visas & Options | Nanak Migration Group",
    metaDescription: "The section 48 bar prevents most onshore visa applications after a refusal or cancellation. Exempt visas, offshore options and ART review explained. MARN 2619467.",
    primaryKeyword: "section 48 bar Australia exempt visas",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "pic-4020": {
    title: "PIC 4020 — False Information & Bogus Documents | Nanak Migration Group",
    metaDescription: "PIC 4020 is the integrity criterion that triggers a 3-year or 10-year visa ban for false information or bogus documents. Waiver guide and response advice. MARN 2619467.",
    primaryKeyword: "PIC 4020 false information bogus document visa refusal",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "reviews": {
    title: "Client Reviews | Nanak Migration Group — MARN 2619467",
    metaDescription: "Verified Google reviews from clients of Nanak Migration Group (MARN 2619467) — MARA-registered migration agents serving Australia in English, Punjabi and Hindi.",
    primaryKeyword: "nanak migration group reviews",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "news": {
    title: "Immigration News | Nanak Migration Group — MARN 2619467",
    metaDescription: "Australian immigration news, policy updates, occupation list changes and fee indexation from MARA-registered agents at Nanak Migration Group (MARN 2619467).",
    primaryKeyword: "australian immigration news 2026",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "training-visa-407": {
    title: "Training Visa (Subclass 407) | Nanak Migration Group",
    metaDescription: "The subclass 407 Training visa allows eligible people to undertake occupational training in Australia to improve skills. Sponsor required. MARN 2619467.",
    primaryKeyword: "training visa subclass 407 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "short-stay-specialist-400": {
    title: "Short Stay Specialist Visa (Subclass 400) | Nanak Migration Group",
    metaDescription: "The subclass 400 Temporary Work (Short Stay Specialist) visa is for highly specialised non-ongoing work in Australia — typically up to 3 months. No sponsorship required. MARN 2619467.",
    primaryKeyword: "short stay specialist visa subclass 400 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "temporary-activity-408": {
    title: "Temporary Activity Visa (Subclass 408) | Nanak Migration Group",
    metaDescription: "The subclass 408 Temporary Activity visa covers entertainment, sport, research, religious work, exchange and government-endorsed events in Australia. MARN 2619467.",
    primaryKeyword: "temporary activity visa subclass 408 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "dama": {
    title: "Designated Area Migration Agreements (DAMA) | Nanak Migration Group",
    metaDescription: "DAMAs give regional employers access to concessions on salary, age and English unavailable under standard 482 pathways. Two-stage endorsement and visa process explained. MARN 2619467.",
    primaryKeyword: "designated area migration agreement DAMA Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "skilled-regional-887": {
    title: "Skilled Regional (Permanent) Visa Subclass 887 | Nanak Migration Group",
    metaDescription: "The subclass 887 Skilled Regional visa grants permanent residence to holders of eligible provisional regional visas (489, 475, 487). Requirements: 2 years regional residence and 1 year full-time regional work. MARN 2619467.",
    primaryKeyword: "skilled regional 887 visa permanent residence Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "invitation-rounds": {
    title: "SkillSelect Invitation Rounds Explained | Nanak Migration Group",
    metaDescription: "How SkillSelect invitation rounds work for the 189 and family-sponsored 491 visa — points cutoffs, round results, state nomination timelines, and common myths. MARN 2619467.",
    primaryKeyword: "SkillSelect invitation rounds Australia 189 visa cutoff",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "child-visa-101": {
    title: "Child Visa (Subclass 101) Offshore | Nanak Migration Group",
    metaDescription: "The subclass 101 Child visa grants permanent residence to a dependent child applying from outside Australia whose parent is an Australian citizen, PR or eligible NZ citizen. MARN 2619467.",
    primaryKeyword: "child visa subclass 101 offshore Australia permanent",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "child-visa-802": {
    title: "Child Visa (Subclass 802) Onshore | Nanak Migration Group",
    metaDescription: "The subclass 802 Child visa grants permanent residence to a dependent child already in Australia whose parent is an Australian citizen, PR or eligible NZ citizen. Bridging visa during processing. MARN 2619467.",
    primaryKeyword: "child visa subclass 802 onshore Australia permanent",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "parent-visa-103": {
    title: "Parent Visa (Subclass 103) | Nanak Migration Group",
    metaDescription: "The subclass 103 Parent visa is a non-contributory offshore permanent parent visa. Much lower government charges than the 143 but a realistic processing wait of around 30 years for new applications. MARN 2619467.",
    primaryKeyword: "parent visa subclass 103 Australia non-contributory",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "assurance-of-support": {
    title: "Assurance of Support (AoS) for Australian Parent Visas | Nanak Migration Group",
    metaDescription: "Assurance of Support explained — who must provide it, the income test, the refundable bank bond, and how the AoS period and bond amounts differ between contributory and non-contributory parent visas. MARN 2619467.",
    primaryKeyword: "assurance of support Australia parent visa AoS",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "carer-visa": {
    title: "Carer Visa (Subclass 116 & 836) | Nanak Migration Group",
    metaDescription: "The Carer visa (subclass 116 offshore, 836 onshore) grants permanent residence to a person who provides substantial care to an Australian relative with a long-term medical condition. MARN 2619467.",
    primaryKeyword: "carer visa subclass 116 836 Australia permanent",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "remaining-relative-visa": {
    title: "Remaining Relative Visa (Subclass 115 & 835) | Nanak Migration Group",
    metaDescription: "The Remaining Relative visa (subclass 115 offshore, 835 onshore) is for people whose only near relatives all live in Australia. Strict eligibility, capped and queued — new applications face a multi-decade wait. MARN 2619467.",
    primaryKeyword: "remaining relative visa subclass 115 835 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "working-holiday-417": {
    title: "Working Holiday Visa (Subclass 417) | Nanak Migration Group",
    metaDescription: "The Working Holiday visa (subclass 417) lets eligible young people from partner countries holiday and work in Australia for 12 months. Second and third year grants available via regional work. MARN 2619467.",
    primaryKeyword: "working holiday visa subclass 417 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "work-and-holiday-462": {
    title: "Work and Holiday Visa (Subclass 462) | Nanak Migration Group",
    metaDescription: "The Work and Holiday visa (subclass 462) is for nationals from countries including the USA, China, India, Vietnam and Indonesia. Country-specific requirements and ballot system explained. MARN 2619467.",
    primaryKeyword: "work and holiday visa subclass 462 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "protection-visa-866": {
    title: "Protection Visa (Subclass 866) | Nanak Migration Group",
    metaDescription: "The Protection visa (subclass 866) is Australia",
    primaryKeyword: "protection visa subclass 866 Australia refugee",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "schedule-3": {
    title: "Schedule 3 Criteria for Partner Visas | Nanak Migration Group",
    metaDescription: "Schedule 3 imposes additional criteria on unlawful non-citizens and some bridging visa holders applying for a partner visa onshore. Criteria 3001, 3003 and 3004, compelling reasons waiver, and the Waensila decision explained. MARN 2619467.",
    primaryKeyword: "schedule 3 partner visa Australia compelling reasons waiver",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "no-further-stay-8503": {
    title: "No Further Stay Condition 8503 — Waiver Guide | Nanak Migration Group",
    metaDescription: "Condition 8503 prevents most onshore visa applications. Which visas carry it, VEVO check process, the two-part waiver test (compelling and compassionate, unforeseeable), and the protection visa exception. MARN 2619467.",
    primaryKeyword: "condition 8503 no further stay waiver Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "health-waiver": {
    title: "Health Requirement Waivers — PIC 4005 & PIC 4007 | Nanak Migration Group",
    metaDescription: "PIC 4005 (no waiver) versus PIC 4007 (waiver available) health criteria explained. Medical Officer of the Commonwealth opinion, undue cost and prejudice test, process and evidence guide. MARN 2619467.",
    primaryKeyword: "health requirement waiver PIC 4007 Australia visa",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "re-entry-bans": {
    title: "Re-entry Bans and Exclusion Periods — PIC 4013 & PIC 4014 | Nanak Migration Group",
    metaDescription: "PIC 4013 (cancellation) and PIC 4014 (departing unlawful) exclusion periods explained. The 28-day departure window, section 501 character bans, waiver for partner visas, and planning a lawful return. MARN 2619467.",
    primaryKeyword: "re-entry ban exclusion period PIC 4013 4014 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "temporary-work-403": {
    title: "Temporary Work (International Relations) Visa (Subclass 403) | Nanak Migration Group",
    metaDescription: "The subclass 403 Temporary Work (International Relations) visa covers five streams: Government Agreement, Foreign Government Agency, Domestic Worker (Diplomatic), Privileges and Immunities, and the Pacific Australia Labour Mobility (PALM) scheme. Registered agent MARN 2619467.",
    primaryKeyword: "temporary work international relations visa subclass 403 PALM scheme Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "adoption-visa-102": {
    title: "Adoption Visa (Subclass 102) | Nanak Migration Group",
    metaDescription: "The Adoption visa (subclass 102) is a permanent visa for a child adopted outside Australia by an Australian citizen, PR or eligible NZ citizen. Intercountry and expatriate adoption pathways explained. Registered agent MARN 2619467.",
    primaryKeyword: "adoption visa subclass 102 Australia intercountry adoption",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "dependent-child-445": {
    title: "Dependent Child Visa (Subclass 445) | Nanak Migration Group",
    metaDescription: "The Dependent Child visa (subclass 445) lets a child join a parent who holds a temporary partner visa (309 or 820) in Australia. Temporary visa — child must be included in the parent",
    primaryKeyword: "dependent child visa subclass 445 temporary partner visa Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "contributory-aged-parent-884": {
    title: "Contributory Aged Parent (Temporary) Visa Subclass 884 | Nanak Migration Group",
    metaDescription: "The subclass 884 Contributory Aged Parent (Temporary) visa is a 2-year onshore visa for pension-age parents, splitting contributory charges before transitioning to the permanent subclass 864. Balance of Family test applies. MARN 2619467.",
    primaryKeyword: "contributory aged parent visa subclass 884 temporary Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "natural-justice-s57": {
    title: "Natural Justice and Section 57 Letters | Nanak Migration Group",
    metaDescription: "Section 57 of the Migration Act requires the Department to put adverse information to an applicant before refusing. What counts, strict response timeframes, how to respond well, PIC 4020 risk, and getting urgent help. MARN 2619467.",
    primaryKeyword: "section 57 natural justice letter adverse information visa Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "eta-601": {
    title: "Electronic Travel Authority (ETA) Subclass 601 | Nanak Migration Group",
    metaDescription: "ETA subclass 601: digital entry authority for eligible passport holders (USA, Canada, Japan, South Korea, Singapore, and others) via the Australian ETA app. Small service charge, multiple 3-month visits in 12 months, tourism and business visitor only. MARN 2619467.",
    primaryKeyword: "electronic travel authority ETA subclass 601 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "evisitor-651": {
    title: "eVisitor Subclass 651 | Nanak Migration Group",
    metaDescription: "eVisitor subclass 651: free entry authority for eligible European passport holders — EU member states and other eligible European nations. Multiple 3-month visits in 12 months, tourism and business visitor purposes only, applied via ImmiAccount. MARN 2619467.",
    primaryKeyword: "eVisitor subclass 651 Australia European passport",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "medical-treatment-602": {
    title: "Medical Treatment Visa Subclass 602 | Nanak Migration Group",
    metaDescription: "Medical Treatment visa subclass 602: for patients seeking medical treatment in Australia, supporting carers, and organ donors. Confirmed treatment arrangements required; no work rights; cannot be used for surrogacy. MARN 2619467.",
    primaryKeyword: "medical treatment visa subclass 602 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "special-category-444": {
    title: "Special Category Visa Subclass 444 for New Zealand Citizens | Nanak Migration Group",
    metaDescription: "Special Category visa subclass 444: granted automatically to New Zealand citizens on arrival in Australia. Full work and study rights, Medicare access, indefinite stay while in Australia. Direct citizenship pathway available since July 2023. MARN 2619467.",
    primaryKeyword: "special category visa 444 New Zealand citizens Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "ministerial-intervention": {
    title: "Ministerial Intervention Sections 351 and 417 | Nanak Migration Group",
    metaDescription: "Ministerial intervention under sections 351 and 417 of the Migration Act: a last-resort discretionary power, not a review right. The Minister cannot be compelled to intervene. Only a small fraction of requests succeed. Lodging a request does not give bridging visa status. MARN 2619467.",
    primaryKeyword: "ministerial intervention section 351 417 visa Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "aged-dependent-relative": {
    title: "Aged Dependent Relative Visa Subclass 114 and 838 | Nanak Migration Group",
    metaDescription: "Aged Dependent Relative visa subclass 114 (offshore) and 838 (onshore): permanent residence for a single, pension-age relative who has been financially dependent on an Australian relative for at least 3 years. Capped and queued — long wait. MARN 2619467.",
    primaryKeyword: "aged dependent relative visa subclass 114 838 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "orphan-relative-visa": {
    title: "Orphan Relative Visa Subclass 117 and 837 | Nanak Migration Group",
    metaDescription: "Orphan Relative visa subclass 117 (offshore) and 837 (onshore): permanent visa for a child under 18 whose parents are deceased, permanently incapacitated, or of unknown whereabouts — sponsored by an eligible Australian relative. MARN 2619467.",
    primaryKeyword: "orphan relative visa subclass 117 837 Australia child",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
  "nz-family-relationship-461": {
    title: "New Zealand Citizen Family Relationship Visa Subclass 461 | Nanak Migration Group",
    metaDescription: "Subclass 461 NZ Citizen Family Relationship visa: 5-year temporary visa for family members (not NZ citizens) of a New Zealand citizen on a subclass 444 Special Category visa in Australia. Full work and study rights. Renewable onshore. MARN 2619467.",
    primaryKeyword: "NZ citizen family relationship visa subclass 461 Australia",
    keywords: "",
    h1: "",
    body: "",
    heroImage: "",
  },
};
